using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;
using PetHealthcare.Domain.Models;

namespace PetHealthcare.DataAccess.Configurations
{
    internal class VisitConfiguration : IEntityTypeConfiguration<Visit>
    {
        public void Configure(EntityTypeBuilder<Visit> builder)
        {
            builder.HasData(
            new Visit { Id = 1, PetId = 1, VetId = 1, DateOfVisit = DateTime.Parse("2018-05-25"), VisitType = "Shelter Care", Reason = "Shelter Initial Evaluation", Weight = 13.0, Diagnosis = "Heartworm Positive", Prescriptions = "Heartworm (oral), Flea and Tick (topical)", Instructions = "None", Notes = "None", Heartworm = false, Bordatella = true, Rabies = false, Da2ppv = false, Leptospirosis = false, InfluenzaH3N2 = false, InfluenzaH3N8 = false, FecalTest = false, OtherTests = "SNAP Heartworm Test", OwnedBy = "6de17564-15cd-412f-9804-537b7cbeb4c8" },
            new Visit { Id = 2, PetId = 1, VetId = 1, DateOfVisit = DateTime.Parse("2018-06-08"), VisitType = "Shelter Care", Reason = "Shelter Care: DHPP Shot", Weight = 13.0, Diagnosis = "None", Prescriptions = "None", Instructions = "None", Notes = "None", Heartworm = false, Bordatella = false, Rabies = false, Da2ppv = true, Leptospirosis = false, InfluenzaH3N2 = false, InfluenzaH3N8 = false, FecalTest = false, OtherTests = "None", OwnedBy = "6de17564-15cd-412f-9804-537b7cbeb4c8" },
            new Visit { Id = 3, PetId = 1, VetId = 1, DateOfVisit = DateTime.Parse("2018-06-10"), VisitType = "Shelter Care", Reason = "Shelter Care: Deworming", Weight = 13.0, Diagnosis = "None", Prescriptions = "Pyrantel Pamoate 50mg/mL 1 x daily", Instructions = "See prescription", Notes = "Deworming prescription", Heartworm = false, Bordatella = false, Rabies = false, Da2ppv = false, Leptospirosis = false, InfluenzaH3N2 = false, InfluenzaH3N8 = false, FecalTest = false, OtherTests = "None", OwnedBy = "6de17564-15cd-412f-9804-537b7cbeb4c8" },
            new Visit { Id = 4, PetId = 1, VetId = 2, DateOfVisit = DateTime.Parse("2018-06-15"), VisitType = "Shelter Care", Reason = "Austin Pets Alive Initial Care", Weight = 13.0, Diagnosis = "None", Prescriptions = "None", Instructions = "None", Notes = "Terrified. Flea dirty. Lean. Quiet, Alert, Responsive.", Heartworm = false, Bordatella = false, Rabies = false, Da2ppv = false, Leptospirosis = false, InfluenzaH3N2 = false, InfluenzaH3N8 = false, FecalTest = false, OtherTests = "Intake Exam", OwnedBy = "6de17564-15cd-412f-9804-537b7cbeb4c8" },
            new Visit { Id = 5, PetId = 1, VetId = 4, DateOfVisit = DateTime.Parse("2018-06-23"), VisitType = "Shelter Care", Reason = "DAPPv shot", Weight = 13.0, Diagnosis = "None", Prescriptions = "None", Instructions = "None", Notes = "None", Heartworm = false, Bordatella = false, Rabies = false, Da2ppv = false, Leptospirosis = false, InfluenzaH3N2 = false, InfluenzaH3N8 = false, FecalTest = false, OtherTests = "None", OwnedBy = "6de17564-15cd-412f-9804-537b7cbeb4c8" },
            new Visit { Id = 6, PetId = 1, VetId = 3, DateOfVisit = DateTime.Parse("2018-07-10"), VisitType = "Shelter Care", Reason = "Distemper Clearance Exam", Weight = 13.0, Diagnosis = "Cleared", Prescriptions = "None", Instructions = "None", Notes = "Cleared for Distemper. Was in foster care for 3-4 weeks. No sign of GI or URI. Bright Alert Responsive. Very nervous.", Heartworm = false, Bordatella = false, Rabies = false, Da2ppv = false, Leptospirosis = false, InfluenzaH3N2 = false, InfluenzaH3N8 = false, FecalTest = false, OtherTests = "None", OwnedBy = "6de17564-15cd-412f-9804-537b7cbeb4c8" },
            new Visit { Id = 7, PetId = 1, VetId = 4, DateOfVisit = DateTime.Parse("2018-07-22"), VisitType = "Shelter Care", Reason = "Spay", Weight = 13.0, Diagnosis = "None", Prescriptions = "Tramodol as needed", Instructions = "See prescription", Notes = "Routine ovariohysterectomy", Heartworm = false, Bordatella = false, Rabies = false, Da2ppv = false, Leptospirosis = false, InfluenzaH3N2 = false, InfluenzaH3N8 = false, FecalTest = false, OtherTests = "None", OwnedBy = "6de17564-15cd-412f-9804-537b7cbeb4c8" },
            new Visit { Id = 8, PetId = 2, VetId = 5, DateOfVisit = DateTime.Parse("2018-07-23"), VisitType = "Annual Exam", Reason = "Initial Exam", Weight = 9.4, Diagnosis = "Heartworm Negative", Prescriptions = "Heartgard Plus K9 S 1-25lb, Nexgard K9 Blue Md 1-24lb", Instructions = "None", Notes = "First visit post-adoption. Estimate 1 year old = Birthday 23 Jul 2017.", Heartworm = false, Bordatella = true, Rabies = true, Da2ppv = true, Leptospirosis = true, InfluenzaH3N2 = true, InfluenzaH3N8 = true, FecalTest = true, OtherTests = "Heartworm", OwnedBy = "6de17564-15cd-412f-9804-537b7cbeb4c8" },
            new Visit { Id = 9, PetId = 2, VetId = 5, DateOfVisit = DateTime.Parse("2018-08-13"), VisitType = "Shots Due", Reason = "Shot booster update", Weight = 9.4, Diagnosis = "None", Prescriptions = "None", Instructions = "None", Notes = "Follow up shots for initial exam.", Heartworm = false, Bordatella = false, Rabies = false, Da2ppv = true, Leptospirosis = false, InfluenzaH3N2 = true, InfluenzaH3N8 = true, FecalTest = true, OtherTests = "None", OwnedBy = "6de17564-15cd-412f-9804-537b7cbeb4c8" },
            new Visit { Id = 10, PetId = 2, VetId = 5, DateOfVisit = DateTime.Parse("2018-09-07"), VisitType = "Routine", Reason = "Health Certificate Domestic", Weight = 9.5, Diagnosis = "None", Prescriptions = "None", Instructions = "None", Notes = "Clearance to fly", Heartworm = false, Bordatella = false, Rabies = false, Da2ppv = false, Leptospirosis = false, InfluenzaH3N2 = false, InfluenzaH3N8 = false, FecalTest = false, OtherTests = "None", OwnedBy = "6de17564-15cd-412f-9804-537b7cbeb4c8" },
            new Visit { Id = 11, PetId = 1, VetId = 4, DateOfVisit = DateTime.Parse("2018-12-02"), VisitType = "Routine", Reason = "Adoption", Weight = 13.0, Diagnosis = "None", Prescriptions = "None", Instructions = "Heartworm Treatment Planning", Notes = "Adoption Day", Heartworm = false, Bordatella = false, Rabies = false, Da2ppv = false, Leptospirosis = false, InfluenzaH3N2 = false, InfluenzaH3N8 = false, FecalTest = false, OtherTests = "None", OwnedBy = "6de17564-15cd-412f-9804-537b7cbeb4c8" },
            new Visit { Id = 12, PetId = 2, VetId = 5, DateOfVisit = DateTime.Parse("2018-12-11"), VisitType = "Minor Incident", Reason = "Minor dog bite", Weight = 9.9, Diagnosis = "No breaks", Prescriptions = "Cefpodoxime 100mg, Rovera (Carprofen) 25mg", Instructions = "None", Notes = "X-rays and Cleanup", Heartworm = false, Bordatella = false, Rabies = false, Da2ppv = false, Leptospirosis = false, InfluenzaH3N2 = false, InfluenzaH3N8 = false, FecalTest = false, OtherTests = "None", OwnedBy = "6de17564-15cd-412f-9804-537b7cbeb4c8" },
            new Visit { Id = 13, PetId = 1, VetId = 6, DateOfVisit = DateTime.Parse("2018-12-20"), VisitType = "Annual Exam", Reason = "Initial VCA Arbor Exam", Weight = 11.5, Diagnosis = "None", Prescriptions = "Heartgard Plus K9 S 1-25lb, Nexgard K9 Blue Md 10.1-24lb", Instructions = "None", Notes = "None", Heartworm = false, Bordatella = false, Rabies = false, Da2ppv = false, Leptospirosis = false, InfluenzaH3N2 = false, InfluenzaH3N8 = false, FecalTest = false, OtherTests = "None", OwnedBy = "6de17564-15cd-412f-9804-537b7cbeb4c8" },
            new Visit { Id = 14, PetId = 1, VetId = 6, DateOfVisit = DateTime.Parse("2018-12-29"), VisitType = "Routine", Reason = "Radiograph Thorax", Weight = 11.1, Diagnosis = "Slight enlargement", Prescriptions = "Prednisolone 5mg", Instructions = "No decongestants or fever reducers (toxic)", Notes = "None", Heartworm = false, Bordatella = false, Rabies = false, Da2ppv = false, Leptospirosis = false, InfluenzaH3N2 = false, InfluenzaH3N8 = false, FecalTest = false, OtherTests = "None", OwnedBy = "6de17564-15cd-412f-9804-537b7cbeb4c8" },
            new Visit { Id = 15, PetId = 2, VetId = 6, DateOfVisit = DateTime.Parse("2020-10-08"), VisitType = "Annual Exam", Reason = "Annual Exam", Weight = 11.3, Diagnosis = "Healthy", Prescriptions = "Flea and Tick (oral)", Instructions = "None", Notes = "None", Heartworm = true, Bordatella = true, Rabies = false, Da2ppv = false, Leptospirosis = true, InfluenzaH3N2 = false, InfluenzaH3N8 = false, FecalTest = false, OtherTests = "Heartworm", OwnedBy = "6de17564-15cd-412f-9804-537b7cbeb4c8" },
            new Visit { Id = 16, PetId = 1, VetId = 6, DateOfVisit = DateTime.Parse("2020-10-08"), VisitType = "Annual Exam", Reason = "Annual Exam", Weight = 12.8, Diagnosis = "Healthy", Prescriptions = "Flea and Tick (oral)", Instructions = "None", Notes = "None", Heartworm = true, Bordatella = true, Rabies = false, Da2ppv = false, Leptospirosis = true, InfluenzaH3N2 = false, InfluenzaH3N8 = false, FecalTest = false, OtherTests = "Heartworm", OwnedBy = "6de17564-15cd-412f-9804-537b7cbeb4c8" }
                );
        }
    }
}